<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DemandOrientationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('demand_orientation_type')->truncate();
        \DB::table('demand_orientation_type')->insert(array(
            0 => array(
                'subject' => 'Subject Test 1',
                'demand_id' => 2,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 1,
                'user_transacting' => rand(1, 30),
                'date' => date("Y-m-d"),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            1 => array(
                'subject' => 'Subject Test 2',
                'demand_id' => 3,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 2,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            2 => array(
                'subject' => 'Subject Test 3',
                'demand_id' => 4,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 3,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            3 => array(
                'subject' => 'Subject Test 4',
                'demand_id' => 5,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 4,
                'user_transacting' => rand(1, 30),
                'date' => date("Y-m-d"),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            4 => array(
                'subject' => 'Subject Test 5',
                'demand_id' => 5,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                'status' => 1,
                'sort_order' => 5,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            5 => array(
                'subject' => 'Subject Test 6',
                'demand_id' => 6,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit..',
                'status' => 1,
                'sort_order' => 6,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            6 => array(
                'subject' => 'Subject Test 7',
                'demand_id' => 7,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 7,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            7 => array(
                'subject' => 'Subject Test 8',
                'demand_id' => 8,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 8,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            8 => array(
                'subject' => 'Subject Test 9',
                'demand_id' => 9,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 9,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            9 => array(
                'subject' => 'Subject Test 10',
                'demand_id' => 10,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 10,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            10 => array(
                'subject' => 'Subject Test 11',
                'demand_id' => 11,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 11,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            11 => array(
                'subject' => 'Subject Test 12',
                'demand_id' => 12,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 12,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            12 => array(
                'subject' => 'Subject Test 13',
                'demand_id' => 13,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 13,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            13 => array(
                'subject' => 'Subject Test 14',
                'demand_id' => 14,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 14,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            14 => array(
                'subject' => 'Subject Test 15',
                'demand_id' => 15,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 15,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            15 => array(
                'subject' => 'Subject Test 16',
                'demand_id' => 16,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 16,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),

            16 => array(
                'subject' => 'Subject Test 17',
                'demand_id' => 17,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 17,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            17 => array(
                'subject' => 'Subject Test 18',
                'demand_id' => 18,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 18,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            18 => array(
                'subject' => 'Subject Test 19',
                'demand_id' => 19,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 19,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            19 => array(
                'subject' => 'Subject Test 20',
                'demand_id' => 20,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 20,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            20 => array(
                'subject' => 'Subject Test 21',
                'demand_id' => 21,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 21,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            21 => array(
                'subject' => 'Subject Test 22',
                'demand_id' => 22,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 22,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            22 => array(
                'subject' => 'Subject Test 23',
                'demand_id' => 25,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 23,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            23 => array(
                'subject' => 'Subject Test 24',
                'demand_id' => 1,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 24,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            24 => array(
                'subject' => 'Subject Test 25',
                'demand_id' => 1,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 25,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            25 => array(
                'subject' => 'Subject Test 26',
                'demand_id' => 1,
                'type' =>1,
                'where' => 'Kaymakamlık',
                'chase_status' => rand(0,1),
                'date' => date("Y-m-d"),
                'description' =>'Lorem ipsum dolor sit amet consectetur adipisicing elit',
                'status' => 1,
                'sort_order' => 26,
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),


        ));
    }
}
