<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DfntnDatatypeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('dfntn_data_type')->truncate();
        \DB::table('dfntn_data_type')->insert([
            [
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 1,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 2,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 3,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 4,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 5,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 6,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 7,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 8,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 9,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 10,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 11,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 12,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 13,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 14,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 15,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 16,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 17,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 18,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 19,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 20,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 21,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 22,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 23,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 24,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 25,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 26,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 27,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 28,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 29,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 30,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 31,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 32,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 33,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 34,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 35,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 36,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 37,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 38,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 39,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 40,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 41,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 42,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
			[
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 43,
                'status' => 1,
				'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 44,
                'status' => 1,
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 45,
                'status' => 1,
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 46,
                'status' => 1,
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 47,
                'status' => 1,
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 48,
                'status' => 1,
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 49,
                'status' => 1,
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 50,
                'status' => 1,
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 51,
                'status' => 1,
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 52,
                'status' => 1,
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 53,
                'status' => 1,
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 54,
                'status' => 1,
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 55,
                'status' => 1,
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 56,
                'status' => 1,
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'DTYPE-' . date_format(date_create(date('Ymdhis')), 'U'),
                'sort_order' => 57,
                'status' => 1,
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ]
		]);
        \DB::table('dfntn_data_type_translation')->truncate();
        \DB::table('dfntn_data_type_translation')->insert([
            [
                'data_type_id' => 1,
                'language_code' => 'tr',
                'name' => 'Cinsiyet yönelim',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 1,
                'language_code' => 'en',
                'name' => 'Gender orientation',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 2,
                'language_code' => 'tr',
                'name' => 'Cinsiyet kimlik ',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 2,
                'language_code' => 'en',
                'name' => 'Gender identity',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 3,
                'language_code' => 'tr',
                'name' => 'Medeni Hal',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 3,
                'language_code' => 'en',
                'name' => 'Marital Status',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 4,
                'language_code' => 'tr',
                'name' => 'Evlilik Türkiyede Resmi Midir',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 4,
                'language_code' => 'en',
                'name' => 'Marriage Formal Turkey',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 5,
                'language_code' => 'tr',
                'name' => 'Basvuran Hassasiyet',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 5,
                'language_code' => 'en',
                'name' => 'Applicant Sensitivity',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 6,
                'language_code' => 'tr',
                'name' => 'Eğitim',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 6,
                'language_code' => 'en',
                'name' => 'Education',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 7,
                'language_code' => 'tr',
                'name' => 'Başvuru Yeri',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 7,
                'language_code' => 'en',
                'name' => 'Application Place',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 8,
                'language_code' => 'tr',
                'name' => 'Başvuru Yolu',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 8,
                'language_code' => 'en',
                'name' => 'Application Pathe',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 9,
                'language_code' => 'tr',
                'name' => 'Mülteci Durum',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 9,
                'language_code' => 'en',
                'name' => 'Refugee Status',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 10,
                'language_code' => 'tr',
                'name' => 'Kim Başvurdu',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 10,
                'language_code' => 'en',
                'name' => 'Who Applied',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 11,
                'language_code' => 'tr',
                'name' => 'Proje Katılım',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 11,
                'language_code' => 'en',
                'name' => 'Project Participation',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 12,
                'language_code' => 'tr',
                'name' => 'Avukat Gerekli Mi',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 12,
                'language_code' => 'en',
                'name' => 'Is Lawyer Required',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 13,
                'language_code' => 'tr',
                'name' => 'Gerekli Yasal Yardım',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 13,
                'language_code' => 'en',
                'name' => 'Legal Aid',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 14,
                'language_code' => 'tr',
                'name' => 'Hangi Sıklıkla Takip Edilir',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 14,
                'language_code' => 'en',
                'name' => 'With which to follow',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 15,
                'language_code' => 'tr',
                'name' => 'Türkiyede hiç doğum yapmış mı',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 15,
                'language_code' => 'en',
                'name' => 'Have you ever done birth in Turkey',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 16,
                'language_code' => 'tr',
                'name' => 'Yenidoğan İçin Ne Tür Belge Düzenlendi',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 16,
                'language_code' => 'en',
                'name' => 'What Kind of Document Is Held For A Newborn',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 17,
                'language_code' => 'tr',
                'name' => 'Kontraseptif kullanımı',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 17,
                'language_code' => 'en',
                'name' => 'Contraceptive use',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 18,
                'language_code' => 'tr',
                'name' => 'Mevcut durum',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 18,
                'language_code' => 'en',
                'name' => 'Current state',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 19,
                'language_code' => 'tr',
                'name' => 'Eğer işe alınmışsa',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 19,
                'language_code' => 'en',
                'name' => 'If the in job has been received',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 20,
                'language_code' => 'tr',
                'name' => 'Başvuran İşi Nasıl Bulmuştur',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 20,
                'language_code' => 'en',
                'name' => 'How the applicant found the job',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 21,
                'language_code' => 'tr',
                'name' => 'Çalışansa Çocuğunun Günlük Bakım',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 21,
                'language_code' => 'en',
                'name' => 'Daily Care of Employee Child',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 22,
                'language_code' => 'tr',
                'name' => 'İstihdam türü',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 22,
                'language_code' => 'en',
                'name' => 'Employment type',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 23,
                'language_code' => 'tr',
                'name' => 'İstihdam sektörü',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 23,
                'language_code' => 'en',
                'name' => 'Employment sector',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 24,
                'language_code' => 'tr',
                'name' => 'Gelir',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 24,
                'language_code' => 'en',
                'name' => 'Income',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 25,
                'language_code' => 'tr',
                'name' => 'Gelir kaynakları',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 25,
                'language_code' => 'en',
                'name' => 'Sources of income',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 26,
                'language_code' => 'tr',
                'name' => 'Nerede çalışıyor',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 26,
                'language_code' => 'en',
                'name' => 'Where does it work',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 27,
                'language_code' => 'tr',
                'name' => 'Her hangi bir saldırıya ugramış mı',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 27,
                'language_code' => 'en',
                'name' => 'Has it been attacked by any',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 28,
                'language_code' => 'tr',
                'name' => 'Faaliyet raporu modülü',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 28,
                'language_code' => 'en',
                'name' => 'Annual report module',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 29,
                'language_code' => 'tr',
                'name' => 'Durum',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 29,
                'language_code' => 'en',
                'name' => 'Status',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 30,
                'language_code' => 'tr',
                'name' => 'Göç Nedeni',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 30,
                'language_code' => 'en',
                'name' => 'Reason of Migration',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 31,
                'language_code' => 'tr',
                'name' => 'Başvuran BMMYKya kayıtlı mı?',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 31,
                'language_code' => 'en',
                'name' => 'Is the applicant registered with UNHCR?',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 32,
                'language_code' => 'tr',
                'name' => 'Evet ise kim?',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 32,
                'language_code' => 'en',
                'name' => 'If yes who?',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 33,
                'language_code' => 'tr',
                'name' => 'Menşei ülkede akraba kaldı mı?',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 33,
                'language_code' => 'en',
                'name' => 'Has it remained related in the country of origin?',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 34,
                'language_code' => 'tr',
                'name' => 'Başka ülkede akrabası var mı?',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 34,
                'language_code' => 'en',
                'name' => 'Does have a relative in another country?',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 35,
                'language_code' => 'tr',
                'name' => 'Konut Tipi',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 35,
                'language_code' => 'en',
                'name' => 'Housing Type',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 36,
                'language_code' => 'tr',
                'name' => 'Alınan Hizmet Türü',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 36,
                'language_code' => 'en',
                'name' => 'Service Type',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 37,
                'language_code' => 'tr',
                'name' => 'Hangi sıklıkla takip ediliyor',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 37,
                'language_code' => 'en',
                'name' => 'How often is it followed',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 38,
                'language_code' => 'tr',
                'name' => 'Çocuklar okula neden okula gitmiyor ',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 38,
                'language_code' => 'en',
                'name' => 'Why dont children go to school',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 39,
                'language_code' => 'tr',
                'name' => 'Sağlık Problemleri',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 39,
                'language_code' => 'en',
                'name' => 'Health problems',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 40,
                'language_code' => 'tr',
                'name' => 'Başvuru Tipi',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 40,
                'language_code' => 'en',
                'name' => 'Application Type',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 41,
                'language_code' => 'tr',
                'name' => 'SGBV Tipi',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 41,
                'language_code' => 'en',
                'name' => 'SGBV Type',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 42,
                'language_code' => 'tr',
                'name' => 'SGBV Uygulayan Kişi',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 42,
                'language_code' => 'en',
                'name' => 'Person applying SGBV',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 43,
                'language_code' => 'tr',
                'name' => 'SGBV Olay Yeri',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
			],
            [
                'data_type_id' => 43,
                'language_code' => 'en',
                'name' => 'SGBV Crime Scene',
                'date_modified' => date("Y-m-d H:i:s"),
				'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 44,
                'language_code' => 'tr',
                'name' => 'Öğrenim Şekli',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 44,
                'language_code' => 'en',
                'name' => 'Education Mode',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 45,
                'language_code' => 'tr',
                'name' => 'Öğrenim Durumu',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 45,
                'language_code' => 'en',
                'name' => 'Education Status',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 46,
                'language_code' => 'tr',
                'name' => 'Aile',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 46,
                'language_code' => 'en',
                'name' => 'Family',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 47,
                'language_code' => 'tr',
                'name' => 'Sağlık Sorunları',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 47,
                'language_code' => 'en',
                'name' => 'Health Problems',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 48,
                'language_code' => 'tr',
                'name' => 'Devam',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 48,
                'language_code' => 'en',
                'name' => 'Continue',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 49,
                'language_code' => 'tr',
                'name' => 'Sağlık Kurumları',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 49,
                'language_code' => 'en',
                'name' => 'Health institutions',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 50,
                'language_code' => 'tr',
                'name' => 'Kontraseptif',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 50,
                'language_code' => 'en',
                'name' => 'Contraceptive',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 51,
                'language_code' => 'tr',
                'name' => 'Kontraseptif Sorumlu',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 51,
                'language_code' => 'en',
                'name' => 'Contraceptive Responsible',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 52,
                'language_code' => 'tr',
                'name' => 'Hangi Kurum',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 52,
                'language_code' => 'en',
                'name' => 'Which Institution',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 53,
                'language_code' => 'tr',
                'name' => 'Belge',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 53,
                'language_code' => 'en',
                'name' => 'Documenet',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 54,
                'language_code' => 'tr',
                'name' => 'Talep Sahibi',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 54,
                'language_code' => 'en',
                'name' => 'Demand Owner',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 55,
                'language_code' => 'tr',
                'name' => 'Uygulama Yöntemi',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 55,
                'language_code' => 'en',
                'name' => 'Application Method',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 56,
                'language_code' => 'tr',
                'name' => 'Yönlendirme Türü',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 56,
                'language_code' => 'en',
                'name' => 'orientation  Type',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 57,
                'language_code' => 'tr',
                'name' => 'Yönlendirme Takip Durumu',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'data_type_id' => 57,
                'language_code' => 'en',
                'name' => 'orientation  Chase Status',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ]
		]);
    }
}
