<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class IndividualEmploymentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('individual_emloyment')->truncate();
        \DB::table('individual_emloyment')->insert(array(
            0 => array(
                'individual_id' => 1,
                'permit_status' => rand(1,3),
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price' => 2500,
                'employment_description'=> 'Lorem Lorem Lorem',
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            1 => array(
                'individual_id' => 1,
                'permit_status'=> rand(1,3),
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id'=> rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price'=> 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created'=> date("Y-m-d H:i:s"),
            ),
            2 => array(
                'individual_id'=> 1,
                'permit_status' => rand(1,3),
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price' => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            3 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price' => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            4 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price' => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            5 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price' => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            6 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price' => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            7 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price' => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            8 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'user_transacting' => rand(1, 30),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'income_price' => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' =>'Evet',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            9 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id'=> rand(1,10),
                'employment_sector_id' => rand(1,6),
                'user_transacting' => rand(1, 30),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'income_price' => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            10 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'user_transacting' => rand(1, 30),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'income_price' => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            11 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price' => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            12 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price' => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            13 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price'  => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' =>'Evet',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            14 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price'  => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description'  => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            15 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price'   => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),

            16 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id'  => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price'  => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            17 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price'  => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description'=> 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            18 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price'=> 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description'  => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            19 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price' => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            20 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price' => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            21 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price'  => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description'=> 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            22 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id'  => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price' => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            23 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price'  => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description'  => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            24 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id' => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price' => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            25 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'sgk_status' => rand(0,2),
                'sgk_number'=>123456789,
                'employment_type_id'  => rand(1,10),
                'employment_sector_id' => rand(1,6),
                'working_hours' =>'08:30-20:30',
                'income_type_id' => rand(1,11),
                'user_transacting' => rand(1, 30),
                'income_price' => 2500,
                'employment_work_start' => date("Y-m-d"),
                'employment_work_end' => date("Y-m-d"),
                'employment_description' => 'Lorem Lorem Lorem',
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            )

        ));
    }
}
