<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class IndividualFamilyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('individual_family')->truncate();
        \DB::table('individual_family')->insert(array(
            0 => array(
                'individual_id'               => 1,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            1 => array(
                'individual_id'               => 2,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            2 => array(
                'individual_id'               => 3,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            3 => array(
                'individual_id'               => 4,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            4 => array(
                'individual_id'               => 5,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            5 => array(
                'individual_id'               => 6,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            6 => array(
                'individual_id'               => 7,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            7 => array(
                'individual_id'               => 8,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            8 => array(
                'individual_id'               => 9,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            9 => array(
                'individual_id'               => 10,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            10 => array(
                'individual_id'               => 11,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            11 => array(
                'individual_id'               => 12,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            12 => array(
                'individual_id'               => 13,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            13 => array(
                'individual_id'               => 14,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            14 => array(
                'individual_id'               => 15,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            15 => array(
                'individual_id'               => 16,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),

            16 => array(
                'individual_id'               => 17,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            17 => array(
                'individual_id'               => 18,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            18 => array(
                'individual_id'               => 19,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            19 => array(
                'individual_id'               => 20,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            20 => array(
                'individual_id'               => 21,
                'relationship'                => rand(1,11),
                'gender'                      => rand(1,6),
                'user_transacting' => rand(1, 30),
                'name_surname'                => 'Abdullmuttalip Samedov',
                'birth_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            )

        ));
    }
}
