<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class IndividualHealthInfoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('individual_health_info')->truncate();
        \DB::table('individual_health_info')->insert(array(
            0 => array(
                'individual_id'                => 1,
                'health_institution'           => rand(1,6),
                'contraceptive_method'         => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'     => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'                => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation'         => rand(0,2),
                'sex_reassignment_psychiatric' =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'                => date("Y-m-d H:i:s"),
                'date_created'                 => date("Y-m-d H:i:s"),
            ),
            1 => array(
                'individual_id'                => 2,
                'health_institution' => rand(1,6),
                'contraceptive_method' => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'  =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),
            2 => array(
                'individual_id'  => 3,
                'health_institution'     => rand(1,6),
                'contraceptive_method'    => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),
            3 => array(
                'individual_id'               => 4,
                'health_institution'     => rand(1,6),
                'contraceptive_method'    => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),
            4 => array(
                'individual_id'  => 5,
                'health_institution'     => rand(1,6),
                'contraceptive_method'    => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),
            5 => array(
                'individual_id' => 6,
                'health_institution'     => rand(1,6),
                'contraceptive_method'    => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),
            6 => array(
                'individual_id' => 7,
                'health_institution'     => rand(1,6),
                'contraceptive_method'    => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),
            7 => array(
                'individual_id'   => 8,
                'health_institution'   => rand(1,6),
                'contraceptive_method'    => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),
            8 => array(
                'individual_id'   => 9,
                'health_institution'     => rand(1,6),
                'contraceptive_method'    => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),
            9 => array(
                'individual_id'   => 10,
                'health_institution'     => rand(1,6),
                'contraceptive_method'    => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),
            10 => array(
                'individual_id' => 11,
                'health_institution'  => rand(1,6),
                'contraceptive_method'    => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),
            11 => array(
                'individual_id' => 12,
                'health_institution'     => rand(1,6),
                'contraceptive_method'    => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),
            12 => array(
                'individual_id'  => 13,
                'health_institution'   => rand(1,6),
                'contraceptive_method'  => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),
            13 => array(
                'individual_id'  => 14,
                'health_institution'  => rand(1,6),
                'contraceptive_method'  => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),
            14 => array(
                'individual_id' => 15,
                'health_institution' => rand(1,6),
                'contraceptive_method'  => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),
            15 => array(
                'individual_id'  => 16,
                'health_institution'  => rand(1,6),
                'contraceptive_method'  => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),

            16 => array(
                'individual_id' => 17,
                'health_institution' => rand(1,6),
                'contraceptive_method' => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),
            17 => array(
                'individual_id' => 18,
                'health_institution'  => rand(1,6),
                'contraceptive_method'  => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),
            18 => array(
                'individual_id'  => 19,
                'health_institution' => rand(1,6),
                'contraceptive_method' => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),
            19 => array(
                'individual_id' => 20,
                'health_institution'  => rand(1,6),
                'contraceptive_method'  => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            ),
            20 => array(
                'individual_id'  => 21,
                'health_institution' => rand(1,6),
                'contraceptive_method' => rand(1,6),
                'contraceptive_responsible' => rand(0,1),
                'easy_healthcare_facility'  => rand(0,2),
                'sexually_transmitted_disease' => rand(0,2),
                'change_gender'  => rand(0,2),
                'hormonal_treatment'           =>  rand(0,2),
                'sex_change_operation' => rand(0,2),
                'sex_reassignment_psychiatric'  =>  rand(0,2),
                'user_transacting' => rand(1, 30),
                'date_modified'  => date("Y-m-d H:i:s"),
                'date_created'  => date("Y-m-d H:i:s"),
            )

        ));
    }
}
