<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class IndividualEmploymentInfoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('individual_emloyment_info')->truncate();
        \DB::table('individual_emloyment_info')->insert(array(
            0 => array(
                'individual_id'               => 1,
                'permit_status'               => 1,
                'vocational_education_status' => 1,
                'child_day_care'              => 'Mother',
                'outcoming_country_job'       => 'Cleaner',
                'incoming_country_job'        => 'Cleaner',
                'sexual_harassment'           => 'No',
                'gender_based_discrimination' => 'No',
                'sexual_orientation'          => 'No',
                'mobbing'                     => 'No',
                'user_transacting' => rand(1, 30),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            1 => array(
                'individual_id'               => 1,
                'permit_status'               => 1,
                'vocational_education_status' => 1,
                'child_day_care'              => 'Father',
                'outcoming_country_job'       => 'Caregiver',
                'incoming_country_job'        => 'Housewife',
                'sexual_harassment'           => 'No',
                'gender_based_discrimination' => 'No',
                'sexual_orientation'          => 'No',
                'mobbing'                     => 'No',
                'user_transacting' => rand(1, 30),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            2 => array(
                'individual_id'               => 1,
                'permit_status'               => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Anne',
                'outcoming_country_job' => 'Bakkal',
                'incoming_country_job' => 'öğretmen',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            3 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Hala',
                'outcoming_country_job' => 'Aşcı',
                'incoming_country_job' => 'öğretmen',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            4 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Anne',
                'outcoming_country_job' => 'Bekci',
                'incoming_country_job' => 'Mühemdis',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            5 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Anne',
                'outcoming_country_job' => 'Yazılımcı',
                'incoming_country_job' => 'Yazılımcı',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            6 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Amca',
                'outcoming_country_job' => 'İnşaat işcisi',
                'incoming_country_job' => 'Diş Hekimi',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            7 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Baba',
                'outcoming_country_job' => 'Kasiyer',
                'incoming_country_job' => 'Kasiyer',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            8 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Anne',
                'outcoming_country_job' => 'Kasiyer',
                'incoming_country_job' => 'öğretmen',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Evet',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Evet',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            9 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Amca',
                'outcoming_country_job' => 'Garson',
                'incoming_country_job' => 'Müdür',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            10 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Teyze',
                'outcoming_country_job' => 'Barista',
                'incoming_country_job' => 'Barista',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            11 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Anne',
                'outcoming_country_job' => 'Barmen',
                'incoming_country_job' => 'Barmen',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            12 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Anne',
                'outcoming_country_job' => 'Sucu',
                'incoming_country_job' => 'Müdür',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            13 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Baba',
                'outcoming_country_job' => 'Çöpcü',
                'incoming_country_job' => 'öğretmen',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Evet',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            14 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Abla',
                'outcoming_country_job' => 'Kasap',
                'incoming_country_job' => 'Doktor',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            15 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Anne',
                'outcoming_country_job' => 'Garson',
                'incoming_country_job' => 'öğretmen',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),

            16 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Anne',
                'outcoming_country_job' => 'Bakkal',
                'incoming_country_job' => 'Doktor',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            17 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Hala',
                'outcoming_country_job' => 'Kasiyer',
                'incoming_country_job' => 'Mühendis',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            18 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Anne',
                'outcoming_country_job' => 'Öğrenci',
                'incoming_country_job' => 'Öğrenci',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            19 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Baba',
                'outcoming_country_job' => 'Yok',
                'incoming_country_job' => 'Doktor',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            20 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Anne',
                'outcoming_country_job' => 'Yok',
                'incoming_country_job' => 'Bakıcı',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            21 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Anne',
                'outcoming_country_job' => 'Kasiyer',
                'incoming_country_job' => 'Güvenlik',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            22 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Abi',
                'outcoming_country_job' => 'Berber',
                'incoming_country_job' => 'Berber',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            23 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Dayı',
                'outcoming_country_job' => 'Doktor',
                'incoming_country_job' => 'Doktor',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            24 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Dayı',
                'outcoming_country_job' => 'Mühendis',
                'incoming_country_job' => 'Mühendis',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ),
            25 => array(
                'individual_id' => 1,
                'permit_status' => 1,
                'vocational_education_status' => 1,
                'child_day_care'=>'Amca',
                'outcoming_country_job' => 'Aşcı',
                'incoming_country_job' => 'Hemşire',
                'sexual_harassment' =>'Hayır',
                'gender_based_discrimination' => 'Hayır',
                'sexual_orientation' => 'Hayır',
                'mobbing' =>'Hayır',
                'user_transacting' => rand(1, 30),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            )

        ));
    }
}
