<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class IndividualHouseholdInfoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('individual_household_info')->truncate();
        \DB::table('individual_household_info')->insert(array(
            0 => array(
                'individual_id'               => 1,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'        => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            1 => array(
                'individual_id'               => 2,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            2 => array(
                'individual_id'               => 3,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            3 => array(
                'individual_id'               => 4,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            4 => array(
                'individual_id'               => 5,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            5 => array(
                'individual_id'               => 6,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            6 => array(
                'individual_id'               => 7,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            7 => array(
                'individual_id'               => 8,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            8 => array(
                'individual_id'               => 9,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            9 => array(
                'individual_id'               => 10,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            10 => array(
                'individual_id'               => 11,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            11 => array(
                'individual_id'               => 12,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            12 => array(
                'individual_id'               => 13,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            13 => array(
                'individual_id'               => 14,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            14 => array(
                'individual_id'               => 15,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            15 => array(
                'individual_id'               => 16,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),

            16 => array(
                'individual_id'               => 17,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            17 => array(
                'individual_id'               => 18,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            18 => array(
                'individual_id'               => 19,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            19 => array(
                'individual_id'               => 20,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            20 => array(
                'individual_id'               => 21,
                'permit_status'               => rand(0,2),
                'marital_status'              => rand(1,4),
                'gender_id'                   => rand(1,6),
                'age'                         => 28,
                'user_transacting' => rand(1, 30),
                'name_surname'                 => 'Maher Salid',
                'relationship'                => 'Brother',
                'work'                        => 'Software Developer',
                'price'                       => '7000',
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            )

        ));
    }
}
