<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class IndividualUrgentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('individual_urgent')->truncate();
        \DB::table('individual_urgent')->insert(array(
            0 => array(
                'individual_urgent_id'               =>  1,
                'individual_id'                      =>  1,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            1 => array(
                'individual_urgent_id'               =>  2,
                'individual_id'                      =>  2,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            2 => array(
                'individual_urgent_id'               =>  3,
                'individual_id'                      =>  3,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            3 => array(
                'individual_urgent_id'               =>  4,
                'individual_id'                      =>  4,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            4 => array(
                'individual_urgent_id'               =>  5,
                'individual_id'                      =>  5,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            5 => array(
                'individual_urgent_id'               =>  6,
                'individual_id'                      =>  6,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            6 => array(
                'individual_urgent_id'               =>  7,
                'individual_id'                      =>  7,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            7 => array(
                'individual_urgent_id'               =>  8,
                'individual_id'                      =>  8,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            8 => array(
                'individual_urgent_id'               =>  9,
                'individual_id'                      =>  9,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            9 => array(
                'individual_urgent_id'               =>  10,
                'individual_id'                      =>  10,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            10 => array(
                'individual_urgent_id'               =>  11,
                'individual_id'                      =>  11,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            11 => array(
                'individual_urgent_id'               =>  12,
                'individual_id'                      =>  12,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            12 => array(
                'individual_urgent_id'               =>  13,
                'individual_id'                      =>  13,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            13 => array(
                'individual_urgent_id'               =>  14,
                'individual_id'                      =>  14,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            14 => array(
                'individual_urgent_id'               =>  15,
                'individual_id'                      =>  15,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            15 => array(
                'individual_urgent_id'               =>  16,
                'individual_id'                      =>  16,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),

            16 => array(
                'individual_urgent_id'               =>  17,
                'individual_id'                      =>  17,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            17 => array(
                'individual_urgent_id'               =>  18,
                'individual_id'                      =>  18,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            18 => array(
                'individual_urgent_id'               =>  19,
                'individual_id'                      =>  19,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            19 => array(
                'individual_urgent_id'               =>  20,
                'individual_id'                      =>  20,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Father',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            20 => array(
                'individual_urgent_id'               =>  21,
                'individual_id'                      =>  21,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Uncle',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            21 => array(
                'individual_urgent_id'               =>  22,
                'individual_id'                      =>  22,
                'first_name'                         => 'Yusuf',
                'last_name'                          => 'Genç',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            22 => array(
                'individual_urgent_id'               =>  23,
                'individual_id'                      =>  23,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            23 => array(
                'individual_urgent_id'               =>  24,
                'individual_id'                      =>  24,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Sister',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            24 => array(
                'individual_urgent_id'               =>  25,
                'individual_id'                      =>  25,
                'first_name'                         => 'Hakan',
                'last_name'                          => 'Yurt',
                'relationship'                       => 'Father',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            ),
            25 => array(
                'individual_urgent_id'               =>  26,
                'individual_id'                      =>  26,
                'first_name'                         => 'Hasan',
                'last_name'                          => 'Yeşil',
                'relationship'                       => 'Mother',
                'gsm_number'                         => '05342536624',
                'email'                              => 'info@gmail.com',
                'date_modified'                      =>  date("Y-m-d H:i:s"),
                'date_created'                       =>  date("Y-m-d H:i:s"),
            )
    
        ));
    }
}
