<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class IndividualLegalApplicationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('individual_legal_application')->truncate();
        \DB::table('individual_legal_application')->insert(array(
            0 => array(
                'individual_id'               => 1,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'         => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            1 => array(
                'individual_id'               => 2,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            2 => array(
                'individual_id'               => 3,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            3 => array(
                'individual_id'               => 4,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            4 => array(
                'individual_id'               => 5,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            5 => array(
                'individual_id'               => 6,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            6 => array(
                'individual_id'               => 7,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            7 => array(
                'individual_id'               => 8,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            8 => array(
                'individual_id'               => 9,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            9 => array(
                'individual_id'               => 10,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            10 => array(
                'individual_id'               => 11,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            11 => array(
                'individual_id'               => 12,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            12 => array(
                'individual_id'               => 13,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            13 => array(
                'individual_id'               => 14,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            14 => array(
                'individual_id'               => 15,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            15 => array(
                'individual_id'               => 16,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),

            16 => array(
                'individual_id'               => 17,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            17 => array(
                'individual_id'               => 18,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            18 => array(
                'individual_id'               => 19,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            19 => array(
                'individual_id'               => 20,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            ),
            20 => array(
                'individual_id'               => 21,
                'legal_subject'               => 'Lorem Lorem Lorem',
                'legal_court'                 => 'Lorem Lorem Lorem',
                'legal_file_number'           => 123456789,
                'user_transacting' => rand(1, 30),
                'legal_current_status'           => 'Lorem Lorem Lorem',
                'legal_date'                  => now(),
                'date_modified'               => date("Y-m-d H:i:s"),
                'date_created'                => date("Y-m-d H:i:s"),
            )

        ));
    }
}
