<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class IndividualTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('individual')->truncate();
        \DB::table('individual')->insert(array(
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Maher",
                'second_name' => "Hoshang",
                'last_name' => "Anil",
                'email_address' => "maher@mail.com",
                'gsm_number' => "96397828283",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "735642565",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' => 'Halep',
                'outcoming_identification_number' => "9967365737",
                'birth_place' => "Dera",
                'birth_date' => "1975-08-22",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                'user_transacting' => 0,
                'status' => rand(0, 1),
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Rokan",
                'second_name' => "",
                'last_name' => "Sona",
                'email_address' => "rokan@mail.com",
                'gsm_number' => "937456245",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "6346735634",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' => 'İdlip',
                'outcoming_identification_number' => "9435625625",
                'birth_place' => "Kabul",
                'birth_date' => "1979-07-19",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Lava",
                'second_name' => "Ronia",
                'last_name' => "	Shade",
                'email_address' => "lava@mail.com",
                'gsm_number' => "937546547",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "3547456356",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' =>'Şam',
                'outcoming_identification_number' => "973456354",
                'birth_place' => "Deyrizor",
                'birth_date' => "1970-01-13",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Yousef",
                'second_name' => "Jahangir",
                'last_name' => "Harran",
                'email_address' => "yousef@mail.com",
                'gsm_number' => "937488284",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "1245634567",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' => 'Humus',
                'outcoming_identification_number' => "953445665",
                'birth_place' => "Tartus",
                'birth_date' => "1999-02-16",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Aişe",
                'second_name' => "Bervo",
                'last_name' => "Aihma",
                'email_address' => "aise@mail.com",
                'gsm_number' => "9376456354",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "2346546745",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' => 'Şam',
                'outcoming_identification_number' => "76856373567",
                'birth_place' => "Lazkiye",
                'birth_date' => "1994-12-01",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Marwa",
                'second_name' => "Larisa",
                'last_name' => "Delavan",
                'email_address' => "marwa@mail.com",
                'gsm_number' => "9376245625",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "245645756",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' =>'Şam',
                'outcoming_identification_number' => "8967967367",
                'birth_place' => "İdlib",
                'birth_date' => "1989-11-11",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Mahmoud",
                'second_name' => "",
                'last_name' => "Karkud",
                'email_address' => "mahmoud@mail.com",
                'gsm_number' => "9371435655",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "3426547345",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' =>'Şam',
                'outcoming_identification_number' => "854674595",
                'birth_place' => "İdlib",
                'birth_date' => "1965-01-01",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Mouhamed",
                'second_name' => "Evan",
                'last_name' => "Aseg",
                'email_address' => "mouhammed@mail.com",
                'gsm_number' => "9374564526",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "4257634746",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' =>'Şam',
                'outcoming_identification_number' => "9764863574",
                'birth_place' => "Rakka",
                'birth_date' => "2000-07-23",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Ahmad",
                'second_name' => "",
                'last_name' => "Anil",
                'email_address' => "ahmad@mail.com",
                'gsm_number' => "9376256424",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "5475683567",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' =>'Şam',
                'outcoming_identification_number' => "9748436457",
                'birth_place' => "Tartus",
                'birth_date' => "2003-05-05",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Jahangir",
                'second_name' => "",
                'last_name' => "Hoshang",
                'email_address' => "jahangir@mail.com",
                'gsm_number' => "93764357345",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "5463756735",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' =>'Şam',
                'outcoming_identification_number' => "9535763576",
                'birth_place' => "Rakka",
                'birth_date' => "1991-09-28",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Zilan",
                'second_name' => "Yalda",
                'last_name' => "Zilga",
                'email_address' => "zilan@mail.com",
                'gsm_number' => "93745765342",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "568534566",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' =>'Şam',
                'outcoming_identification_number' => "9786784778",
                'birth_place' => "Humus",
                'birth_date' => "1985-01-25",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Fatma",
                'second_name' => "Bervan",
                'last_name' => "Bargad",
                'email_address' => "fatma@mail.com",
                'gsm_number' => "937345754654",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "234675656",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' =>'Şam',
                'outcoming_identification_number' => "87695685367",
                'birth_place' => "Halep",
                'birth_date' => "1977-02-22",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Ayham",
                'second_name' => "",
                'last_name' => "Hoshang",
                'email_address' => "ayham@mail.com",
                'gsm_number' => "937635474356",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "3567653873",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' =>'Şam',
                'outcoming_identification_number' => "789478678",
                'birth_place' => "Gazni",
                'birth_date' => "1971-11-02",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Ahmad",
                'second_name' => "Logan",
                'last_name' => "Sirdo",
                'email_address' => "ahmad@mail.com",
                'gsm_number' => "9373246546",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "54374576770",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' =>'Şam',
                'outcoming_identification_number' => "9576733746",
                'birth_place' => "Belh",
                'birth_date' => "1996-07-03",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Omar",
                'second_name' => "",
                'last_name' => "Evaan",
                'email_address' => "omar@mail.com",
                'gsm_number' => "93765467654",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "768947696",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' =>'Şam',
                'outcoming_identification_number' => "9478356836",
                'birth_place' => "Bamyan",
                'birth_date' => "1978-10-14",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Zahra",
                'second_name' => "Saran",
                'last_name' => "Himda",
                'email_address' => "zahra@mail.com",
                'gsm_number' => "93762456435",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "7456843836",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' =>'Şam',
                'outcoming_identification_number' => "8769874678",
                'birth_place' => "Zaho",
                'birth_date' => "2001-01-05",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Noureddine",
                'second_name' => "",
                'last_name' => "Yalda",
                'email_address' => "noureddine@mail.com",
                'gsm_number' => "937654765765",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "1235476788",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' =>'Şam',
                'outcoming_identification_number' => "9576787476",
                'birth_place' => "Şam",
                'birth_date' => "1989-03-01",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Eva",
                'second_name' => "Essa",
                'last_name' => "Yalda",
                'email_address' => "eva@mail.com",
                'gsm_number' => "9374356256",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "6205467404",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' =>'Şam',
                'outcoming_identification_number' => "996779879",
                'birth_place' => "Şam",
                'birth_date' => "2001-12-11",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Darayya",
                'second_name' => "",
                'last_name' => "Mahli",
                'email_address' => "darayya@mail.com",
                'gsm_number' => "93765476546",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "3265434565",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' =>'Şam',
                'outcoming_identification_number' => "9867867876",
                'birth_place' => "Bağdat",
                'birth_date' => "1981-09-27",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Osman",
                'second_name' => "Hussein",
                'last_name' => "Harran",
                'email_address' => "osman@mail.com",
                'gsm_number' => "93764575465",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "457356724",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' =>'Şam',
                'outcoming_identification_number' => "8598798678",
                'birth_place' => "Babil",
                'birth_date' => "1967-01-01",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Saman",
                'second_name' => "",
                'last_name' => "Ton",
                'email_address' => "saman@mail.com",
                'gsm_number' => "937654765554",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "2645546765",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' =>'Şam',
                'outcoming_identification_number' => "8795678678",
                'birth_place' => "El Bab",
                'birth_date' => "1988-04-09",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'code' => 'NDVDL-' . date_format(date_create(date('Ymdhis')), 'U'),
                'first_name' => "Memo",
                'second_name' => "Ahmad",
                'last_name' => "Ton",
                'email_address' => "maher@mail.com",
                'gsm_number' => "93745634565",
                'origin_country_id' => rand(1, 205),
                'origin_identification_number' => "766573557",
                'outcoming_country_id' => rand(1, 205),
                'outcoming_city_id' =>'Şam',
                'outcoming_identification_number' => "9875678457",
                'birth_place' => "Halep",
                'birth_date' => "1977-05-23",
                'gender_identity' => rand(1, 6),
                'reading_status' => rand(1, 2),
                'precision_status' => rand(1, 11),
                 'user_transacting' => 0,
                'status' => rand(0, 1),
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
        ));
       
        \DB::table('individual_language')->truncate();
        \DB::table('individual_language')->insert(array(
            [
                'individual_id' => 1,
                'language_id' => rand(1,2),
                'read_status' => rand(1,6),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' =>  "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 2,
                'language_id' => rand(1,2),
                'read_status' => rand(1,6),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' =>  "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 3,
                'language_id' => rand(1,2),
                'read_status' => rand(1,6),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' =>  "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 4,
                'language_id' => rand(1,2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 5,
                'language_id' => rand(1, 2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0, 1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 6,
                'language_id' => rand(1,2),
                'read_status' => rand(1,6),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 7,
                'language_id' => rand(1,2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 8,
                'language_id' => rand(1, 2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 9,
                'language_id' => rand(1, 2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 10,
                'language_id' => rand(1,2),
                'read_status' => rand(1,6),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 11,
                'language_id' => rand(1,2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 12,
                'language_id' => rand(1,2),
                'read_status' => rand(1,6),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 13,
                'language_id' => rand(1,2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 14,
                'language_id' => rand(1, 2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0, 1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 15,
                'language_id' => rand(1,2),
                'read_status' => rand(1,6),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 16,
                'language_id' => rand(1,2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' =>  "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 17,
                'language_id' => rand(1, 2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' =>  "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 18,
                'language_id' => rand(1,2),
                'read_status' => rand(1,6),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 19,
                'language_id' => rand(1,2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 21,
                'language_id' => rand(1,2),
                'read_status' => rand(1,6),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 22,
                'language_id' => rand(1,2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 23,
                'language_id' => rand(1, 2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' =>  "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 24,
                'language_id' => rand(1, 2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' =>  "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 25,
                'language_id' => rand(1,2),
                'read_status' => rand(1,6),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 26,
                'language_id' => rand(1,2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 27,
                'language_id' => rand(1, 2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' =>  "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 28,
                'language_id' => rand(1,2),
                'read_status' => rand(1,6),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 29,
                'language_id' => rand(1,2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 30,
                'language_id' => rand(1, 2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 31,
                'language_id' => rand(1, 2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 32,
                'language_id' => rand(1, 2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                 'user_transacting' => 0,
                'interview_language' => rand(0,1),
                'learning_place' =>  "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 33,
                'language_id' => rand(1,2),
                'read_status' => rand(1,6),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                'interview_language' => rand(0,1),
                 'user_transacting' => 0,
                'learning_place' => "Turkey",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
            [
                'individual_id' => 34,
                'language_id' => rand(1,2),
                'read_status' => rand(0, 2),
                'write_status' => rand(1,6),
                'speak_status' => rand(1,6),
                'mother_language' => rand(0,1),
                'interview_language' => rand(0,1),
                 'user_transacting' => 0,
                'learning_place' => "Turkey189",
                'date_modified' => date("Y-m-d H:i:s"),
                'date_created' => date("Y-m-d H:i:s"),
            ],
        ));
    }
}